name: Cypress Tests

on: [push]

env:
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
  - run: docker-compuse up -d
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          install: npm install
          start: npm run start
