name: Cypress Tests

on: [push]

env:
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Start containers
  #       run: docker-compose -f "docker-compose.yml" up -d
  # #     # # Install NPM dependencies, cache them correctly
  # #     # # and run all Cypress tests
  # #     # - name: Install dependecies
  # #     #   run: npm install
  cypress-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: npm install
          start: npm run start

